### ISSUE TITLE
大佬怎么用

### ISSUE THREAD

**Issue by XDQhappy** [yanghl12138/NJFU_SEAT#1]
怎么用这个抢座

**Comment by yanghl12138** [comment]
不好意思，去年学校换了新的系统，这个已经失效了（悲）

**Comment by XDQhappy** [comment]
好的好的谢谢大佬，没想到您秒回啊卧槽！

苹果
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanghl12138/NJFU_SEAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月17日(星期五) 晚上11:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanghl12138/NJFU_SEAT] 大佬怎么用 (Issue #1)





 
不好意思，去年学校换了新的系统，这个已经失效了（悲）
